### ISSUE TITLE
I have a error,anybody help me? thanks!

### ISSUE THREAD

**Issue by lovestory** [ckfinder/ckfinder-plugin-database-adapter-php#2]
PHP Fatal error:  Call to undefined method CKSource\CKFinder\Backend\BackendFactory::registerAdapter() in F:\website\ckfinder_sql\ckfinder\plugins\DatabaseAdapter\DatabaseAdapter.php on line 35

the DatabaseAdapter folder I put it on "plugins"
the config.php code：

/*=================================== Backends ========================================*/
// http://docs.cksource.com/ckfinder3-php/configuration.html#configuration_options_backends
$config['backends'][] = array(
    'name'         => 'database_backend',
    'adapter'      => 'database',
    'dsn'          => 'mysql:host=localhost;dbname=ckfinder_sql',
    'tableName'    => 'dbtable',
    'username'     => 'root',
    'password'     => '123456'
);

$config['backends'][] = array(
    'name'         => 'default',
    'adapter'      => 'local',
    'baseUrl'      => '/File/',
//  'root'         => '', // Can be used to explicitly set the CKFinder user files directory.
    'chmodFiles'   => 0777,
    'chmodFolders' => 0755,
    'filesystemEncoding' => 'utf-8',
);

/*================================ Resource Types =====================================*/
// http://docs.cksource.com/ckfinder3-php/configuration.html#configuration_options_resourceTypes

$config['defaultResourceTypes'] = '';

$config['resourceTypes'][] = array(
    'name'              => 'Files', // Single quotes not allowed.
    'directory'         => 'files',
    'maxSize'           => 0,
    'allowedExtensions' => '7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip,xhtml',
    'deniedExtensions'  => '',
    'backend'           => 'default'
);

$config['resourceTypes'][] = array(
    'name'              => 'Images',
    'directory'         => 'images',
    'maxSize'           => 0,
    'allowedExtensions' => 'bmp,gif,jpeg,jpg,png',
    'deniedExtensions'  => '',
    'backend'           => 'default'
);

$config['resourceTypes'][] = array(
    'name'              => 'Database Files',
    'backend'           => 'database_backend'
);

$config['plugins'] = [
	'DatabaseAdapter'
];

**Comment by zaak** [comment]
Hi @lovestory. It's probably an old CKFinder installation. Which CKFinder version do you use? Could you please check if the same happens in [newest version 3.4.2](https://ckeditor.com/ckeditor-4/download/#ckfinder)?

**Comment by lovestory** [comment]
@zaak  Thank you! Then I found the problem I use version is 3.0，I use the 3.4 is successful.
But ckfinder-plugin-database-adapter manual “This is a CKFinder 3 plugin that adds support for storing files in the database.” So I think run it on 3.0. 
thank you so much.
